[workspace]
members = [
    "ipp-ctypes",
    "ipp-headers-sys",
    "ipp-sys-build-help",
    "ipp-sys",
    "link-ippcore",
    "link-ippvm",
    "link-ippcv",
    "link-ippcc",
    "link-ippi",
    "link-ipps",
    ]
